### ISSUE TITLE
God ide MEN kan misbruges.

### ISSUE THREAD

**Issue by benzon** [oMarkez/FSH_GlobalBans#1]
Det er alt for nemt at banne en uskyldig person med sådan et system her, specielt fordi du kun køre op mod din database.

Det er langt mere irriterende og skulle tilføje bypass's da det er manuelt helevejen igennem.

Hvis et system som dette skulle holde en smule vand, skal der mere end en episode til at global banne en person eller uddybende bevis.

og da du giver direkte adgang til databasen, med insert kan den taintes på 10 sekunder, for relt er det bare at lave masse insert, så er der hurtigt 10000 stemid's i databasen.

Der ud over er systemet ikke standalone, men bygget op omkring vRP så globalt bliver det aldrig.

**Comment by oMarkez** [comment]
Nej, jeg giver ikke direkte adgang til databasen, brugeren er oprettet med select-only perms, så det eneste du kan derinde er at selecte kolonner :)

Globalt bliver det ikke, men da 90%+ af danske servere kører med vRP, så vil majoriteten af danske servere kunne bruge dette, så tæt på globalt er det. Jeg har inkluderet "global" i titlen, da man så får en bedre ide omkring funktionen af denne resource.

Bans kommer kun til at blive givet, der hvor der er stærkt grundlag med beviser på en person modder/hacker. Disse bans vil blive postet i min discord, så folk ved hvem bliver bannet, og bansne kan sagtens appeales hvis man kan bevise det modsatte. 

Jeg har kun tilføjet bypasses, sådan at hvis folk der er globally banned kan få en server, og/eller spille på en server hvilket tilgiver hans hændelser. Jeg tænker ikke at der kommer til at være særligt mange bans, og endnu færre som tilgiver person for deres hændeldse, så derfor tror jeg ikke at det er det store problem.

**Comment by benzon** [comment]
Okay så relt set, hvis en server så banner en person, så bliver de ikke bannet i databasen, med mindre i manuelt tilføjer personen, fordi i kan se bannet via den discord webhook der ligger i.

**Comment by oMarkez** [comment]
Ja, det hele køre over min database, og lige pt. er det kun mig der kan tilføje global bans. En servers bans har ingen betydning for global bans.

**Comment by oMarkez** [comment]
Tænker denne issue er løst, hvis ikke skal du være velkommen til at kontakte mig på discord og/eller oprette en ny issue. 

Tak for feedback/kommentaren, det sætter jeg stor pris på :)
